server:
  port: 9000

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#修改访问http://localhost:8761(需要先启动eureka_server)后该应用的Instances currently registered with Eureka的名字
#将来需要使用该名称来获取路径
spring:
  application:
    name: eureka-consumer


#配置文件配置的方式设置Ribbon的负载均衡策略
EUREKA-PROVIDER: #设置的服务提供方的应用名称
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #策略类
