server:
  port: 9000

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#修改访问http://localhost:8761(需要先启动eureka_server)后该应用的Instances currently registered with Eureka的名字
#将来需要使用该名称来获取路径
spring:
  application:
    name: eureka-consumer


#配置文件配置的方式设置Ribbon的负载均衡策略
EUREKA-PROVIDER: #设置的服务提供方的应用名称
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #策略类

#设置超时时间(默认都是1s)
# Feign 客户端默认的 ConnectTimeout 和 ReadTimeout 不会被 Ribbon 配置覆盖(使用了feign后该配置无法起作用)
ribbon:
  ConnectTimeout: 1000 #连接超时时间，毫秒
  ReadTimeout: 3000    #逻辑处理超时时间，毫秒

#设置com包的日志级别debug, feign只支持记录debug级别的日志
logging:
  level:
    com: debug

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 6000
#开启降级策略
  hystrix:
    enabled: true
